### ISSUE TITLE
Date selection is messed up

### ISSUE THREAD

**Issue by nathanmrtns** [lee5783/TLMonthYearPicker#1]
Sometimes if you choose a limit date it messes the whole picker.

For example, if I select 2020 but the max date is 2017 it returns to 2017. Then if I select 2016 it changes the month too.
Sometimes, if I choose, for example, Octubre, the selection changes the selection to September.

**Comment by nathanmrtns** [comment]
It always chooses one down. Ether in .monthAndYear or .year
If I select 2016, it scrolls back to 2015. Similar with month components.

Also, the latest version with cocoa pods is 1.0.2

**Comment by lee5783** [comment]
hi @NathanMrtns 
Pls run 'pod update' command to get latest version '2.0.0' (support Swift 4)
I will change this issue to enhancement
Thank for your feedback!
